name: CI + CD

on:
  push:
    branches: [ develop, staging, main ]
  pull_request:
    branches: [ develop, staging, main ]
  workflow_dispatch:

jobs:
  Build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 3.1.3

      - name: Install dependencies
        run: |
          gem install bundler
          bundle install --jobs 4 --retry 3

      - name: Install gems
        run: |
          bundler install

      # - name: Prepare database
      #   env:
      #     PGHOST: localhost
      #     PGUSER: postgres
      #     PGPASSWORD: postgres
      #     RAILS_ENV: test
      #   run: |
      #     bundle exec rails db:prepare

      - name: Run rspec tests 
        env:
          PGHOST: localhost
          PGUSER: postgres
          PGPASSWORD: postgres
          RAILS_ENV: test
        run: |
          bundle exec rspec

      # - name: Run rubocop 
      #   run: |
      #     bundle exec rubocop

      # - name: Security audit dependencies
      #   run: bundle exec bundler audit --update

      # - name: Security audit application code
      #   run: bundle exec brakeman -q -w2

  DeployStaging:
    name: Deploy to Staging 
    if: github.event_name == 'pull_request' && github.ref == 'refs/heads/staging'
    needs: [Build]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: akhileshns/heroku-deploy@v3.12.12
        with:
          heroku_api_key: ${{secrets.HEROKU_API_KEY}}
          heroku_app_name: "discova-staging"
          heroku_email: "promiseukaimo@gmail.com"


  DeployProd:
    name: Deploy to Production 
    if: github.event_name == 'pull_request' && github.ref == 'refs/heads/main'
    needs: [DeployStaging]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: akhileshns/heroku-deploy@v3.12.12
        with:
          heroku_api_key: ${{secrets.HEROKU_API_KEY}}
          heroku_app_name: "discova-prod"
          heroku_email: "promiseukaimo@gmail.com"

